services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repsy_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repsy_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STORAGE_STRATEGY: file-system
      FILE_STORAGE_LOCATION: /packages
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS-KEY: minio
      MINIO_SECRET-KEY: minio123
    depends_on:
      - postgres
      - minio
    volumes:
      - file-storage:/packages

volumes:
  pgdata:
  minio-data:
  file-storage:
